# Generated by Django 3.2.2 on 2021-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCountDown',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('movieTitle', models.CharField(max_length=250)),
                ('movieDate', models.DateField()),
                ('movieSource', models.CharField(max_length=250)),
            ],
        ),
    ]
